import { world_info } from "../../../world-info.js";

// World Info manipulation functions
export function addWorldInfoEntry(entry) {
    const newEntry = {
        key: entry.suggestedKeys.join(','),
        keysecondary: '',
        comment: `Auto-generated by DynamicLore`,
        content: entry.description,
        constant: false,
        selective: false
    };

    if (world_info && world_info.entries) {
        world_info.entries.push(newEntry);
        if (typeof world_info.sync === 'function') {
            world_info.sync();
        }
    }
}

export function updateWorldInfoEntry(entry) {
    if (!world_info || !world_info.entries) return;

    const existingEntry = world_info.entries.find(e => e.uid === entry.id);
    if (existingEntry) {
        existingEntry.content = entry.mergedContent;
        existingEntry.key = combineKeys(existingEntry.key, entry.suggestedKeys);
        if (typeof world_info.sync === 'function') {
            world_info.sync();
        }
    }
}

function combineKeys(existingKeys, newKeys) {
    const existing = existingKeys.split(',').map(k => k.trim());
    const combined = [...new Set([...existing, ...newKeys])];
    return combined.join(',');
}

function syncWorldInfo() {
    // Save world info and refresh UI
    console.log("World info updated");
}
